#!/bin/bash

name='SOAPHLA'
url="http://soap.genomics.org.cn/down/SOAP-HLA.tar.gz"

get_pkg "$name" "$url"
uncompress_pkg "$name"
move_opt "$name"

DIR="$(opt_dir $name)"

(cd "$DIR";
perl MHC_typing_construct.pl Data_imgt_txt Data_type_hg19 hg19;
perl MHC_typing_construct.pl Data_imgt_txt Data_type_hg18 hg18;
perl MHC_typing_construct.pl Data_imgt_txt Data_type_hg38 hg38;
cat MHC_autopipeline.pl | sed 's/chr6/6/g' > MHC_autopipeline.b37.pl
)

